# Generated by Django 5.0.7 on 2024-07-23 15:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("assistant", "Assistant")], max_length=10
            ),
        ),
        migrations.CreateModel(
            name="Generation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("input_tokens", models.IntegerField()),
                ("output_tokens", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "messages",
                    models.ManyToManyField(
                        related_name="generations", to="api.message"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Generations",
        ),
    ]
