# Generated by Django 5.0.7 on 2024-07-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_conversation_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("assistant", "Assistant")],
                default="user",
                max_length=10,
            ),
        ),
    ]
